- filename: DBLP.bib
  search_type: FEED
  source_name: Americas Confereence on Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: 
        venue_key: conf/amcis
        journal_abbreviated: amcis
  comment: ''
- filename: pdfs.bib
  search_type: FEED
  source_name: AMCIS
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH conference='Americas Conference on Information Systems' AND sub_dir_pattern='year'
  comment: NA
